// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIMS.Data;

#nullable disable

namespace SIMS.API.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20250413080618_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SIMS.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            Colour = "Black",
                            Quantity = 15,
                            Reference = "NK001",
                            Size = "10",
                            UnitPrice = 120.00m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Adidas",
                            Colour = "White",
                            Quantity = 10,
                            Reference = "AD002",
                            Size = "9",
                            UnitPrice = 100.00m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Puma",
                            Colour = "Blue",
                            Quantity = 20,
                            Reference = "PM003",
                            Size = "8",
                            UnitPrice = 90.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
